### ISSUE TITLE
无法运行run.sh

### ISSUE THREAD

**Issue by BlueBlueSloth** [Adrninistrator/java-callgraph2#32]
./run.sh ./android-23.jar
錯誤: 找不到或無法載入主要類別 com.adrninistrator.javacg.stat.JCallGraph
原因: java.lang.ClassNotFoundException: com.adrninistrator.javacg.stat.JCallGraph

**Comment by Adrninistrator** [comment]
使用最新版代码的话，如果是需要编译出jar包来执行，需要按照以下的步骤：

执行`gradlew gen_run_jar`命令，在`jar_output_dir`目录中生成相关的jar包，脚本等

在以上目录中执行`run.sh`脚本，需要分析的jar包需要在配置文件`_javacg_config/jar_dir.properties`中指定
