### ISSUE TITLE
实际代码中找不到<init>方法，但是在line_number这个文件中却有180多行，它是如何解析的？我要怎么check这个行号的正确性

### ISSUE THREAD

**Issue by binghuo15955** [Adrninistrator/java-callgraph2#39]
InternationalFlightItemOrderAgentV2:<init>()	32	213

有什么需要的信息您可以和我说

**Comment by Adrninistrator** [comment]
<init>方法是类的构造函数，代码中定义的非静态字段的初始化之类的操作都会在这个方法里实现，代码里如果不写构造函数，编译器也会生成<init>方法
静态字段的初始化编译后生成在<clinit>方法里
