### ISSUE TITLE
是否支持zip包解析？目前传入zip包后会报错

### ISSUE THREAD

**Issue by binghuo15955** [Adrninistrator/java-callgraph2#46]
![image](https://github.com/Adrninistrator/java-callgraph2/assets/45911100/52d5e2aa-a406-40a1-9952-aef25ba82386)

**Comment by Adrninistrator** [comment]
现在支持是指定jar包，或者jar包、class文件所在的目录如果是jar包解压成zip的话，需要先解压一下，unzip或者jar命令都可以
报错的图片我现在看不到

**Comment by binghuo15955** [comment]
报错的信息：处理单个文件只支持指定.jar或.war格式，加入需要处理.class格式的文件，则需要指定其所在目录。

**Comment by binghuo15955** [comment]
> 现在支持是指定jar包，或者jar包、class文件所在的目录如果是jar包解压成zip的话，需要先解压一下，unzip或者jar命令都可以 报错的图片我现在看不到

我尝试一下，将zip解压后，传入目录

**Comment by binghuo15955** [comment]
> 现在支持是指定jar包，或者jar包、class文件所在的目录如果是jar包解压成zip的话，需要先解压一下，unzip或者jar命令都可以 报错的图片我现在看不到

好像能成，感谢！
